routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::match(array('GET', 'POST'), "/login", array(
    'uses' => 'LoginController@init',
    'as' => 'login'
));
Route::match(array('GET', 'POST'), "/", array(
    'uses' => 'DashboardController@init',
    'as' => 'dashboard'
));
Route::match(array('GET', 'POST'), "logout", array(
    'uses' => 'LogoutController@init',
    'as' => 'logout'
));
Route::match(array('GET', 'POST'), "dashboard", array(
    'uses' => 'DashboardController@init',
    'as' => 'dashboard'
));

Route::match(array('GET', 'POST'), "booklocation", array(
    'uses' => 'BookLocationController@init',
    'as' => 'booklocation'
));

Route::match(array('GET', 'POST'), "booklocation/view/{id}", array(
    'uses' => 'BookLocationController@view',
    'as' => 'booklocation_view'
));

Route::match(array('GET', 'POST'), "booklocation/edit/{id}", array(
    'uses' => 'BookLocationController@edit',
    'as' => 'booklocation_edit'
));

Route::match(array('GET', 'POST'), "booklocation/insert", array(
    'uses' => 'BookLocationController@insert',
    'as' => 'booklocation_insert'
));

Route::match(array('GET', 'POST'), "publish", array(
    'uses' => 'BookPublishController@init',
    'as' => 'publish'
));

Route::match(array('GET', 'POST'), "publish/view/{id}", array(
    'uses' => 'BookPublishController@view',
    'as' => 'publish_view'
));

Route::match(array('GET', 'POST'), "publish/edit/{id}", array(
    'uses' => 'BookPublishController@edit',
    'as' => 'publish_edit'
));

Route::match(array('GET', 'POST'), "publish/insert", array(
    'uses' => 'BookPublishController@insert',
    'as' => 'publish_insert'
));

Route::match(array('GET', 'POST'), "oripublish", array(
    'uses' => 'BookOriPublishController@init',
    'as' => 'oripublish'
));

Route::match(array('GET', 'POST'), "oripublish/view/{id}", array(
    'uses' => 'BookOriPublishController@view',
    'as' => 'oripublish_view'
));

Route::match(array('GET', 'POST'), "oripublish/edit/{id}", array(
    'uses' => 'BookOriPublishController@edit',
    'as' => 'oripublish_edit'
));

Route::match(array('GET', 'POST'), "oripublish/insert", array(
    'uses' => 'BookOriPublishController@insert',
    'as' => 'oripublish_insert'
));

Route::match(array('GET', 'POST'), "category", array(
    'uses' => 'CategoryController@init',
    'as' => 'category'
));

Route::match(array('GET', 'POST'), "category/edit/{id}", array(
    'uses' => 'CategoryController@edit',
    'as' => 'category_edit'
));

Route::match(array('GET', 'POST'), "category/insert", array(
    'uses' => 'CategoryController@insert',
    'as' => 'category_insert'
));

Route::match(array('GET', 'POST'), "translator", array(
    'uses' => 'TranslatorController@init',
    'as' => 'translator'
));

Route::match(array('GET', 'POST'), "translator/edit/{id}", array(
    'uses' => 'TranslatorController@edit',
    'as' => 'translator_edit'
));

Route::match(array('GET', 'POST'), "translator/insert", array(
    'uses' => 'TranslatorController@insert',
    'as' => 'translator_insert'
));

Route::match(array('GET', 'POST'), "manga", array(
    'uses' => 'MangaController@init',
    'as' => 'manga'
));

Route::match(array('GET', 'POST'), "manga/view/{id}", array(
    'uses' => 'MangaController@view',
    'as' => 'manga_view'
));

Route::match(array('GET', 'POST'), "manga/insert", array(
    'uses' => 'MangaController@insert',
    'as' => 'manga_insert'
));

Route::match(array('GET', 'POST'), "novel", array(
    'uses' => 'NovelController@init',
    'as' => 'novel'
));

Route::match(array('GET', 'POST'), "novel/view/{id}", array(
    'uses' => 'NovelController@view',
    'as' => 'novel_view'
));

Route::match(array('GET', 'POST'), "novel/insert", array(
    'uses' => 'NovelController@insert',
    'as' => 'novel_insert'
));

Route::match(array('GET', 'POST'), "author", array(
    'uses' => 'AuthorController@init',
    'as' => 'author'
));

Route::match(array('GET', 'POST'), "author/edit/{id}", array(
    'uses' => 'AuthorController@edit',
    'as' => 'author_edit'
));

Route::match(array('GET', 'POST'), "author/insert", array(
    'uses' => 'AuthorController@insert',
    'as' => 'author_insert'
));

Route::match(array('GET', 'POST'), "unread", array(
    'uses' => 'UnreadController@init',
    'as' => 'unread'
));

Route::match(array('GET', 'POST'), "unread/edit/{id}", array(
    'uses' => 'UnreadController@edit',
    'as' => 'unread_edit'
));

Route::match(array('GET', 'POST'), "newbook", array(
    'uses' => 'NewBookController@init',
    'as' => 'newbook'
));

Route::match(array('GET', 'POST'), "newbook/raw", array(
    'uses' => 'NewBookController@showRawData',
    'as' => 'newbook_raw'
));

Route::match(array('GET', 'POST'), "ajax/callAuthor", array(
    'uses' => 'AjaxController@callAuthor',
    'as' => 'ajax_callAuthor'
));

Route::match(array('GET', 'POST'), "ajax/getMangaDetail", array(
    'uses' => 'AjaxController@getMangaDetail',
    'as' => 'ajax_getMangaDetail'
));

Route::match(array('GET', 'POST'), "ajax/getMangaAuthor/{id}", array(
    'uses' => 'AjaxController@getMangaAuthor',
    'as' => 'ajax_getMangaAuthor'
));

Route::match(array('GET', 'POST'), "ajax/getNovelDetail", array(
    'uses' => 'AjaxController@getNovelDetail',
    'as' => 'ajax_getNovelDetail'
));

Route::match(array('GET', 'POST'), "ajax/getCEDetail", array(
    'uses' => 'AjaxController@getCEDetail',
    'as' => 'ajax_getCEDetail'
));

Route::match(array('GET', 'POST'), "ajax/graph/setAreaGraph", array(
    'uses' => 'AjaxController@setAreaGraph',
    'as' => 'ajax_setAreaGraph'
));

Route::match(array('GET', 'POST'), "ajax/graph/setAreaGraph/{year}", array(
    'uses' => 'AjaxController@setAreaGraph',
    'as' => 'ajax_setAreaGraph'
));

Route::match(array('GET', 'POST'), "ajax/graph/setBarGraph", array(
    'uses' => 'AjaxController@setBarGraph',
    'as' => 'ajax_setBarGraph'
));

Route::match(array('GET', 'POST'), "ajax/graph/setBarReadGraph", array(
    'uses' => 'AjaxController@setBarReadGraph',
    'as' => 'ajax_setBarReadGraph'
));

Route::match(array('GET', 'POST'), "ajax/graph/setDonutGraph", array(
    'uses' => 'AjaxController@setDonutGraph',
    'as' => 'ajax_setDonutGraph'
));

Route::match(array('GET', 'POST'), "ajax/graph/setDonutGraph/{year}", array(
    'uses' => 'AjaxController@setDonutGraph',
    'as' => 'ajax_setDonutGraph'
));

Route::match(array('GET', 'POST'), "comicessay", array(
    'uses' => 'ComicEssayController@init',
    'as' => 'comicessay'
));

Route::match(array('GET', 'POST'), "comicessay/view/{id}", array(
    'uses' => 'ComicEssayController@view',
    'as' => 'comicessay_view'
));

Route::match(array('GET', 'POST'), "comicessay/insert", array(
    'uses' => 'ComicEssayController@insert',
    'as' => 'comicessay_insert'
));

Route::get('/clear-data', function () {
    return view('cleardata');
});

/* command route */
//Clear Cache facade value:
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    return '<h1>Cache facade value cleared</h1>';
});

//Route cache:
Route::get('/route-cache', function() {
    $exitCode = Artisan::call('route:cache');
    return '<h1>Routes cached</h1>';
});

//Clear Route cache:
Route::get('/route-clear', function() {
    $exitCode = Artisan::call('route:clear');
    return '<h1>Route cache cleared</h1>';
});

//Clear View cache:
Route::get('/view-clear', function() {
    $exitCode = Artisan::call('view:clear');
    return '<h1>View cache cleared</h1>';
});

//Clear Config cache:
Route::get('/config-cache', function() {
    $exitCode = Artisan::call('config:cache');
    return '<h1>Clear Config cleared</h1>';
});

Route::get('/clear-compiled', function() {
    $exitCode = Artisan::call('clear-compiled');
    return '<h1>Clear Config cleared</h1>';
});

Route::match(array('GET', 'POST'), "ajax/getMangaRemark", array(
    'uses' => 'AjaxController@getMangaRemark',
    'as' => 'ajax_getMangaRemark'
));

app/BookLocation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Library\Queryhelper;
use DB;

class BookLocation extends Model {

    protected $table = 'book_location';
    const CREATED_AT = NULL;
    const UPDATED_AT = NULL;

    public function mangaDetail() {
        return $this->hasMany('App\MangaDetail','mangaLocation','id');
    }

    public function novelDetail() {
        return $this->hasMany('App\NovelDetail','novelLocation','id');
    }

}

app/Http/Controllers/BookLocationController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Config;
use Session;
use View;
use Route;
use App\BookLocation;
use App\MangaDetail;
use App\NovelDetail;
use App\BookOriPublish;

class BookLocationController extends AuthenController {
    
    private $data = array();

    public function __construct(Request $request) {
        parent::__construct();
        
    }
    
    public function init(Request $request)
    {
        $params = $request->all();

        $search_name = '';
        if(isset($params['search_name'])) {
            $search_name = $params['search_name'];
        }

        //echo '<pre>';print_r($params);echo '</pre>';
        //echo '<pre>';print_r(session()->all());echo '</pre>';

        $whereArr = null;
        $whereArr = [['location', 'like', '%'.$search_name.'%']];
        //$allBookLocation = Booklocation::paginate(10);
        $allBookLocation = Booklocation::withCount('mangaDetail','novelDetail')
                           ->where($whereArr)
                           ->paginate(10);

        //echo '<pre>';print_r($allBookLocation);echo '</pre>';

        $this->data = null;
        $this->data['book_location_list'] = $allBookLocation;
        $this->data['search_name'] = $search_name;

        return view('booklocation.index',$this->data);
    }

    public function view($location_id) {

        $locationInfo = Booklocation::find($location_id); 
        
        $mangaInfo = MangaDetail::with('manga')
                        ->where('mangaLocation',$location_id)
                        ->orderBy('mangaID','asc')
                        ->orderBy('mangaVol','asc')
                        ->get();

        $allOriPublish = BookOriPublish::all();

        foreach($mangaInfo as $obj) {
            $obj->oriPublish = '';
            $tmpName = $allOriPublish->where('id',$obj->manga->oriPublishID)->first();
            if($tmpName != '') {
                $obj->oriPublish = $tmpName->name;
            }
        }

        //echo '<pre>';print_r($mangaInfo[0]);echo '</pre>';

        $novelInfo = NovelDetail::with('novel')
                        ->where('novelLocation',$location_id)
                        ->orderBy('novelID','asc')
                        ->orderBy('novelVol','asc')
                        ->get();

        $this->data = null;
        $this->data['name'] = $locationInfo->location;
        $this->data['mangaList'] = $mangaInfo;
        $this->data['totalManga'] = $mangaInfo->count();
        $this->data['novelList'] = $novelInfo;
        $this->data['totalNovel'] = $novelInfo->count();


        return view('booklocation.view',$this->data);
    }
    
    public function edit(Request $request,$location_id) {
        $params = $request->all();
        //Session::forget('flash_message');

        //echo '<pre>';print_r($params);echo '</pre>';
        //Book::find($id)->update([ 'author_id' => 10]);

        $bookLocationModel = Booklocation::find($location_id);

        if(isset($params['mode'])) {
            if($params['mode'] == 'update') {

                $validatedData = $request->validate([
                    'location' => 'required',
                ], $this->errorMessages() );

                $bookLocationModel->location = $request->location;
                $bookLocationModel->save();

                Session::flash('flash_message', 'updated');
            }
        } 

        $this->data = null;
        $this->data['locationInfo'] = $bookLocationModel;
        return view('booklocation.edit',$this->data);
    }
    
    public function insert(Request $request) {

        $params = $request->all();

        $bookLocationModel = new Booklocation;

        if(isset($params['mode'])) {
            if($params['mode'] == 'insert') { 

                $validatedData = $request->validate([
                    'location' => 'required',
                ], $this->errorMessages() );

                $bookLocationModel->location = $request->location;
                $bookLocationModel->save();
                Session::flash('flash_message', 'inserted');
                return redirect()->route('booklocation_edit', $bookLocationModel->id);
            }
        }

        return view('booklocation.insert');
    }

    public function errorMessages()
    {
        return [
            'location.required' => 'Book Location is required',
        ];
    }    

    /*
สมมติเพนมี
$shops = DB::table('shops')
           ->leftJoin('users', 'shops.account_id', '=', 'users.id')
           ->leftJoin('shop_types', 'shops.shop_type', '=', 'shop_types.id')
           ->leftJoin('shop_categories', 'shops.shop_category', '=', 'shop_categories.id')
           ->leftJoin('floor_zone_mappings', 'shops.zone_mapping_id', '=', 'floor_zone_mappings.id')
           ->leftJoin('floors', 'floor_zone_mappings.floor_id', '=', 'floors.id')
           ->leftJoin('zones', 'floor_zone_mappings.zone_id', '=', 'zones.id')
           ->select('shops.*',
               'users.id as account_id',
               'users.name as account_name',
               'shop_types.name as type_name',
               'shop_categories.name as category_name',
               'zones.name as zone_name',
               'floors.name as floor_name'
           )
           ->get();

$limit = intval(Input::get('limit', 10));
$page = intval(Input::get('page', 1));
$paginator = new LengthAwarePaginator($shops->forPage($page, $limit), $shops->count(), $limit, $page, []);
$dataArray = $paginator->items();
เป็นการสร้าง pagination แบบ custom เอง
โดยใช้  use Illuminate\Pagination\LengthAwarePaginator;
ตอนที่จะ return ไปให้ front ก็ใช้แบบนี้ก็ได้
[
               'rows' => $dataArray,
               'pagination' => [
                   'total_items' => $paginator->total(),
                   'current_page_items' => count($dataArray),
                   'items_per_page' => $paginator->perPage(),
                   'current_page' => $paginator->currentPage(),
                   'total_pages' => $paginator->lastPage(),
               ]
ได้ผลเหมือนกันกับ ::paginate(10)

    */



}

resources/views/booklocation/edit.blade.php
@extends('layouts.master')
@section('content')
<div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Book Location</h3>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <div class="row">
        <div class="panel panel-default">
        <div class="panel-heading clearfix">

          @if (Session::has('flash_message'))
            @if(Session::get('flash_message') == 'updated')
              <div class="alert alert-success">
                <a class="close" data-dismiss="alert">×</a>
                <strong>Done!</strong> Updated success.
              </div>
            @elseif(Session::get('flash_message') == 'inserted')
              <div class="alert alert-success">
                <a class="close" data-dismiss="alert">×</a>
                <strong>Done!</strong> Inserted success.
              </div>
            @else
              <div class="alert alert-danger">
                <a class="close" data-dismiss="alert">×</a>
                  <strong>Error!</strong> Cannot update, please try again.
              </div>
            @endif
          @endif

          @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
          @endif

      <form action="" method="POST" >
        {{ csrf_field() }}
        <div class="form-group">
            <label for="location">Location</label>
            <input type="text" class="form-control" id="location" name="location" value="{{$locationInfo->location}}">
        </div>
        <input type="hidden" name="mode" value="update">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button class="btn btn-default" type="reset">Reset</button>
      </form>

        </div>
        </div>
    </div>
@endsection

resources/views/booklocation/index.blade.php
@extends('layouts.master')
@section('content')
<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Book Location</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <form class="navbar-form navbar-left" role="search">
            {{ csrf_field() }}
            <div class="form-group">
              <input type="text" name="search_name" class="form-control" placeholder="Search" value="{{$search_name}}">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>

          <div class="navbar-form navbar-right">
            <a  href="/booklocation/insert" class="btn btn-info btn-sm" target="_blank">Add a new</a>
          </div>
        </div>
        <!-- panel-heading clearfix -->
      </div>
      <!-- panel panel-default -->

      <!-- Table -->
      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr>
            <th>#</th>
            <th>Location</th>
            <th>Book Quan.</th>
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody>
            @if (isset($book_location_list))
                @foreach($book_location_list as $book_location)
                    <tr>
                        <td>{{$loop->iteration + $book_location_list->firstItem()-1}}</td>
                        <td>{{$book_location->location}}</td>
                        <td>{{$book_location->manga_detail_count + $book_location->novel_detail_count}}</td>
                        <td>
                          <a href="/booklocation/view/{{$book_location->id}}" target="_blank" class="btn btn-info btn-xs" >View</a>
                          <a href="/booklocation/edit/{{$book_location->id}}" target="_blank" class="btn btn-success btn-xs" >Edit</a>
                        </td>
                    </tr>
                @endforeach
            @endif
        </tbody>
      </table>
      <nav style="text-align:center">{{$book_location_list->appends(request()->except('_token'))->links()}}</nav>
</div> <!-- row -- >
@endsection

resources/views/booklocation/insert.blade.php
@extends('layouts.master')
@section('content')
<div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Insert Book Location</h3>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <div class="row">
        <div class="panel panel-default">
        <div class="panel-heading clearfix">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

      <form action="" method="POST" >
        {{ csrf_field() }}
        <div class="form-group">
            <label for="location">Location</label>
            <input type="text" class="form-control" id="location" name="location" value="">
        </div>
        <input type="hidden" name="mode" value="insert">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button class="btn btn-default" type="reset">Reset</button>
      </form>

        </div>
        </div>
    </div>
@endsection

resources/views/booklocation/view.blade.php
@extends('layouts.master')
@section('content')
<div class="row">
        <div class="col-lg-12">
        <h3 class="page-header">{{$name}}</h3>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <div class="row">
      <!-- Nav tabs -->
      <ul class="nav nav-pills">
            <li class="active">
                <a href="#manga" data-toggle="tab"><strong>Manga</strong> <span class="badge">{{$totalManga}}</span></a>
            </li>
            <li>
                <a href="#novel" data-toggle="tab"><strong>Novel</strong> <span class="badge">{{$totalNovel}}</span></a>
            </li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
          
              <div class="tab-pane fade in active" id="manga">
                <br/>
                <div class="panel panel-info">
                <div class="panel-heading">&nbsp;</div>
                <table class="table table-condensed table-bordered" >
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Original Publish</th>
                      <th>Name</th>
                      <th>Native Name</th>
                      <th>Vol.</th>
                      <th>&nbsp;</th>
                    </tr>
                  </thead>
                  <tbody>
                    @if (isset($mangaList) && count($mangaList)>0)
                        @foreach($mangaList as $item)
                            <tr>
                                <td class="text-center">{{$loop->iteration}}</td>
                                <td class="text-center">{{$item->oriPublish}}</td>
                                <td>{{$item->manga->mangaName}}</td>
                                <td>{{$item->manga->mangaNativeName}}</td>
                                <td class="text-center">{{$item->mangaVol}}</td>
                                <td><a href="/manga/view/{{$item->mangaID}}" class="btn btn-info btn-xs" target="_blank" >view</a></td>
                            </tr>
                        @endforeach
                    @else
                        <tr><td colspan="5">&nbsp;</td></tr>
                    @endif
                  </tbody>
                </table>
                </div>
              </div>
              <!-- /.tab-pane fade in  -->

              <div class="tab-pane fade in " id="novel">
                <br/>
                <div class="panel panel-success">
                <div class="panel-heading">&nbsp;</div>
                <table class="table table-condensed table-bordered" >
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Name</th>
                      <th>Native Name</th>
                      <th>Vol.</th>
                      <th>&nbsp;</th>
                    </tr>
                  </thead>
                    @if (isset($novelList) && count($novelList)>0)
                        @foreach($novelList as $item)
                            <tr>
                                <td class="text-center">{{$loop->iteration}}</td>
                                <td>{{$item->novel->novelName}}</td>
                                <td>{{$item->novel->novelNativeName}}</td>
                                <td class="text-center">{{$item->novelVol}}</td>
                                <td><a href="/novel/view/{{$item->novelID}}" class="btn btn-info btn-xs" target="_blank" >view</a></td>
                            </tr>
                        @endforeach
                    @else
                        <tr><td colspan="5">&nbsp;</td></tr>
                    @endif
                  </tbody>
                </table>
                </div>
              </div>
              <!-- /.tab-pane fade in  -->
          
      </div>
    </div>
    <!-- /.row -->
@endsection